import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./components/layout/footer";
import { fetchNavbarItems, getFooter } from "./components/api/getLandingPageData";
import Header, { HeaderItems } from "./components/layout/header";
import CustomHead from "./customHead";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Novotek AI",
  description: "Generated by Novotek AI",
  
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const {menuItems, logoUrl} = await fetchNavbarItems();
    const data = await getFooter();

    const headerItems: HeaderItems = {
      logo: logoUrl || '',
      items: {
        items: menuItems
      }
    };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomHead/>
        <Header {...headerItems} />;
        {children}
        <Footer about={data.about} agency={data.agency} copyright={data.copyright} legalinfo={data.legalinfo}/>
      </body>
    </html>
  );
}
