import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./components/layout/footer";
import { fetchNavbarItems, getFooter } from "./components/api/getLandingPageData";
import Header, { HeaderItems } from "./components/layout/header";
import CustomHead from "./customHead";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const proximaNovaBold = localFont({
  src: [
    { path: './fonts/ProximaNovaLight.woff2', weight: '200' },
    { path: './fonts/ProximaNovaLight.woff', weight: '200' },
    { path: './fonts/ProximaNovaThin.woff2', weight: '300' },
    { path: './fonts/ProximaNovaThin.woff', weight: '300' },
    { path: './fonts/ProximaNovaRegular.woff2', weight: '400' },
    { path: './fonts/ProximaNovaRegular.woff', weight: '400' },
    { path: './fonts/ProximaNovaSemibold.woff2', weight: '600' },
    { path: './fonts/ProximaNovaSemibold.woff', weight: '600' },
    { path: './fonts/ProximaNovaBold.woff2', weight: '700' },
    { path: './fonts/ProximaNovaBold.woff', weight: '700' },
    { path: './fonts/ProximaNovaExtrabold.woff2', weight: '800' },
    { path: './fonts/ProximaNovaExtrabold.woff', weight: '800' },
  ],
  display: 'swap',
  variable: '--font-proxima-nova-bold',
});

export const metadata: Metadata = {
  title: "Novotek AI",
  description: "Generated by Novotek AI",
  
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const {menuItems, logoUrl} = await fetchNavbarItems();
    const data = await getFooter();

    const headerItems: HeaderItems = {
      logo: logoUrl || '',
      items: {
        items: menuItems
      }
    };
  return (
    <html lang="en">
      <body
        className={` ${proximaNovaBold.variable} antialiased`}
      >
        <CustomHead {...headerItems}/>
        <Header {...headerItems} />;
        {children}
        <Footer about={data.about} agency={data.agency} copyright={data.copyright} legalinfo={data.legalinfo}/>
      </body>
    </html>
  );
}
