import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./components/layout/footer";
import { fetchNavbarItems } from "./components/api/getLandingPageData";
import Header from "./components/layout/header";
import CustomHead from "./customHead";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "App Inventive",
  description: "Generated by App Inventiv",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const menuItems = await fetchNavbarItems();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomHead/>
        <Header items={menuItems} />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
